### PR TITLE
Bugfix/ie11 compatibility

### PR DESCRIPTION
**Pull request by dotmagic**
Fix for #4 

I need this for my project and hope you can take a look at it soon.

Thanks

### CODE REVIEW

**Comment by KaneCohen** [comment]
I get error `modal.min.js:1 Uncaught ReferenceError: require is not defined at modal.min.js:1` which is thrown because there's no "require" module available when calling require('events'). I'm afraid webpack would have to be needed to build the dist library.

**Comment by dotmagic** [comment]
@KaneCohen It works well here. I've tested only dist/modal.js with my project that is webpack based too.

I think that may be because you're including a package from node_modules, babel doesn't transpile packages from this folder, but the behavior can be overwritten

**Comment by KaneCohen** [comment]
@dotmagic i see. That would be the problem - since minified file is supposed to be ready for use as is on the web, which therefore must include `events` in order to function properly. I'll manually implement some of the fixes from this PR and update webpack to handle IE11.

**Comment by dotmagic** [comment]
@KaneCohen Okay. Thanks. I don't mind about webpack since it adds only 2-3 KB.

**Comment by KaneCohen** [comment]
Pushed updated version `v0.4.0` - should resolve IE issues.

**Pull request closed without merging**
